vrothberg/vgrep

- vgrep
The '.' is needed for older/Debian/Ubuntu grep.
Signed-off-by: Peter Senna Tschudin<peter.senna@gmail.com>
> Fix behavior for older grep when called with -r

- README.md
- vgrep
For small terminals, or long lines to search, use --no-header to
compress the output a bit more.
> Add --no-header option for people with reduced terminals

- vgrep
On some distributions /usr/bin/python defaults to Python 3. Instead explicitly ask for a valid Python 2 interpreter on the system
> Explicitly specify Python2 as the interpreter

- vgrep
This changes the columns to be right justified for the number columns,
and left justified for "normal" strings.
This uses the format() api, and because of that, we can get rid of the
hand-rolled fill() function, as there are no users of it anymore.
> Right justify numbers, and left justify filenames

- vgrep
Some systems don't have ~/.cache/ so create it before attempting to
write out a file to it.
Problem pointed out by @GeertJohan
> vgrep: if ~/.cache/ is not present, create it

- vgrep
Use "better" defaults for less, and don't use 100 as an arbitrary terminal window size, let less determine it.
> Less tweaks

- vgrep
When writing out the header, having a write call for a character seems
"odd", so put the trailing space on the previous write call.
> vgrep: remove lines that only write one character

- README.md
- vgrep
By default, git submodules are also considered, when git-grep is
used. With --no-git-submodules the old behavior (ignoring
git-submodules) is restored.
> grep: do recursive grep into git-submodules

- vgrep
The filedescriptor object fdc, which holds the output device, shouldn't be
overwritten.
> bugfix: context command

- vgrep
Sometimes you just want to see the help command again, and if you have
already typed a command, you can no longer do that.  So add support for
'?' to be a valid option to show the help again.
> vgrep: add '?' support to -s

- vgrep
Don't really know a better way to show this, perhaps it should be 'h'
instead for "h"elp?
> vgrep: add pseudo-documentation for the '?' interactive command

- vgrep.go
Fix a go-vet error by using the corresponding string instead of
*os.File when printing an os.Open() error.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
> logging: use string instead of *os.File

- vendor.conf
- vendor/github.com/nightlyone/lockfile/LICENSE
- vendor/github.com/nightlyone/lockfile/README.md
- vendor/github.com/nightlyone/lockfile/lockfile.go
- vendor/github.com/nightlyone/lockfile/lockfile_unix.go
- vendor/github.com/nightlyone/lockfile/lockfile_windows.go
- vgrep.go
These commits fix a few different things:
- Spelling mistakes in comments
- When running the `show` command, vgrep would show an "Unsupported command: "s"" warning after closing the editor.
- Sometimes the JSON cache file would be corrupt as the code does not properly wait for the `cacheWrite` goroutine to finish.
> Fixes to command parsing, cache writing and comments 

- go.mod
- vgrep.go
When running inside a vscode terminal, append the line to the file path
so we can quick jump to the specific location.  Thanks to @vbatts for
the idea.
> support vscode

- Dockerfile
Pin the 1.13 and simplify it a bit more.
> Dockerfile: pin to golang:1.13

- vgrep.go
Most terminal emulators use the tango colorscheme by default which has a
very bad contrast when using yellow rendering the lines column very hard
to read.  Change that to magenta to make it easier to read.
> change line color from yellow to magenta

- vgrep.go
Lock directory and cache directory creation were failing when compiling
and running on windows. This fixes the paths to be the windows
equivalents when running on windows.
After this change basic functionality works, on my machine I don't get
any color unless I use the /no-less option, but that's fine.
> Enable basic functionality on windows

- vgrep.go
Drop the `-i` short flag for vgrep's interactive mode.  `-i` is already
in use by grep for case-insensitive search.
Fixes: #62
> drop interactive -i short flag

- vgrep.go
Set cache file mode to 0644, it does not need to be executable.
> Cache file mode 0644

- Makefile
`PREFIX` is a standard variable used for defining the target location of the installation. This patch allows the Makefile to accept this variable without making any other changes.
It also removes the use of `sudo` for the `install` and `uninstall` targets. Not everyone has root access to their computers and the ones who need it should invoke `make install` with the given privileges instead.
> Use a standard variable for setting the installation path

- Makefile
Also install it to `./build` so we're not fighting in GOBIN with other
projects.
> pin golangci-lint version

- Makefile
`install -D` is not available on BSDs and macOS.
AFAIK this `cp` + `chmod` approach will work the same way as `install -D`.
> Cross-platform `make install`

- vgrep.go
based on the grep type select the seperator
and splitting format in splitMatch function
https://github.com/vrothberg/vgrep/issues/79
> fix #79, define a new greptype bsd to select : seperator

- README.md
Clarify that `vgrep` doesn't allow for searching and showing in one
command.  The technical reason for that is to allow for a more
user-friendly way of using the `--show` command.  In particular,
to support `--show x y z` with `x y z` all being arguments for --show
instead of `x` only.
Maybe there are workarounds with other flag-parsing libraries. Something
to look at in the future.
Fixes: #83
> README: clarify search/show

- vgrep.go
For opening a specific line in a file, emacs expects the line argument
before the file path.  Special-case emacs to properly support it.
Reported-by: @snits
> emacs support

- vgrep.go
Some users may be running vgrep in daemon mode.
Reported-by: @snits
> emacs: also account for "emacsclient"

- vgrep.go
When building the grep or ripgrep commands to run, a dot (`.`) is appended to the list of arguments, to indicate that the current working directory should be searched recursively.
Both grep (with its `-r` option) and ripgrep already search the current working directory recursively if no other path is provided. Passing the dot:
- Is useless if no other path (file or directory) to search is provided.
- Adds the content of the whole directory to the list of the files to search, if files or directories were provided on the command line.
This is inconvenient for searching a subdirectory, for example. Typing `vgrep my_pattern foo/` will search for the pattern in files under `foo/` but also in all other files under the current directory, which may take longer and return undesired results.
This …
> grep commands: Do not pass '.' as an argument to grep/ripgrep

- test/simple.bats
- vgrep.go
A third one :).
Vgrep always runs `git rev-parse` to check whether the current directory is a git repository. This is useless if ripgrep is installed, since it is picked by default. Let's run git only if ripgrep is not selected.
Add some tests to check that all expected grep tools are picked, depending on the circumstances. They rely on the debug output to inspect what command is run.
> git grep: Run 'git rev-parse' only if not selecting ripgrep

- README.md
- test/interactive.bats
- test/search_files/foobar.txt
- vgrep.go
The operation used to update the index when deleting a selection of lines is incorrect. Deletions are done sequentially, so after the first deletion, the indices in the list of results have changed and we need to take that into account. But each time we remove an entry, the list of results _shrinks_ by one, so we want a _smaller_ index. The addition in `index := idx + offset` is wrong, it should be a subtraction. Let's fix.
Add a test to validate the results, and document the missing `delete` command in the README.md.
As a side note I initially wrote the test on top of the readline-lib set before rebasing for a clean PR, and it turns out the readline makes it somewhat easier to pass input to vgrep for the tests. In particular, the heredoc accepts more than one line (currently, the `q` is …
> delete: fix index update for multi-line deletions

- internal/colwriter/colwriter.go
- vgrep.go
Having three different fixes to push, I thought they would deserve their own PR after all.
- Fix the command-line editor not being closed on early `os.Exit()` (#106).
- Fix a crash in `colwriter` with `--no-header` if there is no result to print.
- Fix a typo.
> Miscellaneous fixes

- README.md
- test/interactive.bats
- vgrep.go
This PR adds two new commands for further filtering the results in the interactive shell:
- `k`/`keep` does the opposite of `delete`: It keeps only the results for provided indices. Might be useful for keeping a small subset of results, or for filtering on given file (since results are sorted per file, it should be easy to provide a range for the desired file).
- `r`/`refine` restricts the list of results to those matching the provided regular expression.
> Add new "keep" and "refine" commands to the interactive shell

- test/simple.bats
- vgrep.go
Vgrep may fail to parse the output from the selected grep tool, in particular if the user provided some options that modify the output (`-A`, `-B`, `-C`, `-a`, ...). In such a case, splitting the results on the separators will not produce the expected number of substrings and will result in attempts to access incorrect indices in the slice.
Fix `splitMatch()` so vgrep exits gracefully with a hint message when it cannot parse the output.
Add a test for this case.
> splitMatch: fail gracefully on failure to parse output

- README.md
- test/selectors.bats
- vgrep.go
Some vgrep commands (`print`, `context` for example) defaults to processing all search results if no selector is passed. Some other commands (`show`, `delete`) are slightly more sensitive, and they require an explicit set of selectors to indicate the entries to process.
For some commands (`show` in particular), it could be interesting to have a shortcut to tell them “do process all entries, I know what I am doing”. This PR implements a new selector, `all`, that does just that.
A new test file is added to check that selectors are parsed as expected.
> selectors: add a "all" selector to process all results

- Makefile
Remove the `-dev` prefix from `make build` as the VERSION file covers
that now.  Now it's easier to detect a dev version.
> make build: rm `-dev` prefix

- test/simple.bats
- vgrep.go
This mimics the behavior of grep/git-grep and ripgrep, and is useful for chaining a search with a later command:
vgrep "matches zero lines" && vgrep --interactive
As an implementation detail, this commit also reworks the final stages of `main()`, for two reasons:
- to more easily handle in which cases it is necessary to `Wait()`;
- to fix a probable (though not confirmed)[1] bug where a search that resulted in 0 matches would cause the behavior of later commands to be undefined, due to `cacheWrite` not necessarily completing before the program terminated.
[1] In a simple test `cacheWrite` does not complete and leaves the previous search results in place.
> main: exit with 1 if no line is selected

- .goreleaser.yml
This PR adds `goreleaser` support to release static binaries. 
I couldn't find the script that actually releases the project in the repo so I'm just adding this here. In order to release the project using goreleaser, you just need to download the [goreleaser](https://goreleaser.com/install/) tool and run `export GITHUB_TOKEN=$MYTOKEN goreleaser`. 
The above command will automatically perform the release in github, publish the binaries and generate a changelog.
> Add goreleaser config to ship statis binaries

- vgrep.go
When running pager (less) and type CTRL-C, less is not terminated on Windows. I think vgrep should block CTLR-C.
> Handle SIGINT

- Makefile
- docs/vgrep.1.md
Closes #123 
- Update `install` target to download and build `go-md2man` package.
- Add `docs` target to build man page from `README.md` using `go-md2man`.
> Add man page generation to Makefile

- README.md
- docs/vgrep.1.md
- vgrep.go
Change the file format to "$PATH:$LINE" when running inside a Goland
terminal.  `vgrep` already supports VSCode so drop a section to the
README to better communicate this behavior.
> support Goland

- test/simple.bats
- vgrep.go
Support parsing the output of *grep when displaying context lines such
as with `-A`, `-B` or `-C`.
Fixes: #118
> support *grep context options

- Makefile
Use `install` and set propper permissions.
Fixes: #130
> Makefile: fix install targets

- test/simple.bats
- vgrep.go
`vgrep` should print previously cached results when it's run without
grep arguments.  At some yet unknown point in time, we regressed on
it which is calling for regression tests that are now added
Fixes: #132
> vgrep [no grep args]: print matches

- vgrep.go
Use a switch table for dispatching the commands.  It's easier to
brainparse (for me) and the compiler should have an easier time
optimizing.
> use switch table for dispatcher

- README.md
* Interpret ANSI escape sequences to show colors in fzf by using the `--ansi` flag
* Fix syntax error (pipe operator before fzf invocation)
This should fix the remaining issues from https://github.com/vrothberg/vgrep/pull/143
> Fix fzf example

- Dockerfile
In addition to the CI, the build process inside a container should also use a recent Go release.
Signed-off-by: Andreas Ziegler <andreas.ziegler@fau.de>
> Dockerfile: also use golang:1.17

- test/simple.bats
- vgrep.go
Add an option to print the names of matching files in their relative
order.
Closes: #150
> -l, --files-with-matches

- vgrep.go
It should be "--color=auto" not "--color=always" as newer versions of
git will really set the output to color even if it is a pipe like is
happening in vgrep.
Fixes a regression in not working properly with newer versions of git.
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
> Fix 'git grep' color issue reported in Issue #169

- Makefile
Starting with v1.17 `go get` does not install binaries anymore [1],
so use `go install` instead;  Go < v1.17 has been archived.
[1] https://go.dev/doc/go-get-install-deprecation
Fixes: #172
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>
> make .install.go-md2man: use go install

- Dockerfile
So we do not have to worry about updating it after new Go releases.
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>
> Dockerfile: use golang:latest

- vgrep.go
Check for the ripgrep configuration file path env variable and pass it
if it exists.
https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file
> allow ripgrep to use configuration file

- test/editor.bats
- vgrep.go
This adds the environment variable `EDITORLINEFLAGREVERSED`.  If it is set to true, the order of line number and file path is reversed:
| `EDITORLINEFLAGREVERSED` | command |
|----|----|
| 0 / unset | `editor /path/to/file +line` |
| 1 | `editor +line /path/to/file` |
To preserve existing behaviour, the implementation retains the original checks as a fallback.
I wonder what you think, looking forward to your feedback.
> Add environment variable to switch the order of LINEFLAG and file

- vgrep.go
I have no recollection on why vgrep is even storing the indices in the
cache.  The cache is effectively a slice of slices such that indices
are redundant and consume additional disk space and CPU cycles.
Probably worth changing in a future release.
Fixes: #183
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>
> delete/refine: fix adjusting indices

- vgrep.go
Hi,
vgrep doesn't work in OpenBSD by default, because OpenBSD grep has two differences:
1. grep --version output format:
```
$  grep --version
grep version 0.9
```
2. No `--color' parameter.
> Support OpenBSD

- test/errors.bats
- test/helpers.bash
- vgrep.go
Try parsing the stdout of *grep even in case of an error. This allows to return output when hitting, for instance, eperms on certain files.
The stderr of *grep is now logged directly while the exit code is being recorded and used by vgrep on exit.
Fixes: #216
> handle *grep errors

- test/errors.bats
- test/helpers.bash
The tests need to be skipped when running as root, so let's skip them conditionally.
> test/errors.bats: pass as root
